id: P008276
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W3PD358
  title: སྤུ་རྒྱལ་དུས་ཀྱི་བང་སོའི་ཞིབ་འཇུག་ལས་འཕྲོས་པའི་གཏམ།
  author: ''
  volumes:
    53637a5559ae4d4fa75a723bd6baa54d:
      image_group_id: I4PD4682
      title: ''
      volume_number: 1
      total_pages: 230
      base_file: v001.txt
